/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.blz.linkedlistmain.runner;

public class MyNode<T> {
	private T key;
	private MyNode<T> next;

	// Parameterized Constructor
	public MyNode(T key) {
		this.key = key;
		this.next = null;
	}

	public T getKey() {
		return key;
	}

	public void setKey(T key) {
		this.key = key;
	}

	public MyNode<T> getNext() {
		return next;
	}

	public void setNext(MyNode<T> next) {
		this.next = next;
	}
}
