/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.blz.linkedlisttest.tester;

import org.junit.Test;

import com.blz.linkedlistmain.runner.MyNode;

import static org.junit.Assert.*;

import org.junit.Assert;

public class MyNodeTest {
    @Test 
    public void testGiven3NumbersWhenLinkedShouldPassLinkedList() {
    	MyNode<Integer> firstNode=new MyNode<>(56);
    	MyNode<Integer> secondNode=new MyNode<>(30);
    	MyNode<Integer> thirdNode=new MyNode<>(70);
    	
    	firstNode.setNext(secondNode);
    	secondNode.setNext(thirdNode);
    	
    	boolean result=firstNode.getNext().equals(secondNode) && secondNode.getNext().equals(thirdNode);
    	Assert.assertTrue(result);
    }
}
